---
# Welcome to Shipyard! To get started, run `docker compose up -d`
# You can configure your container here, by modifying this file
services:
  shipyard:
    container_name: Shipyard

    # Pull latest image from DockerHub
    image: khulnasoft/shipyard

    # To build from source, replace 'image: khulnasoft/shipyard' with 'build: .'
    # build: .

    # You can also use an image with a different tag, or pull from a different registry, e.g:
    # image: ghcr.io/khulnasoft/shipyard or image: khulnasoft/shipyard:3.0.0

    # Pass in your config file below, by specifying the path on your host machine
    # volumes:
      # - /path/to/my-config.yml:/app/user-data/conf.yml
      # - /path/to/item-icons:/app/user-data/item-icons/

    # Set port that web service will be served on. Keep container port as 8080
    ports:
      - 4000:8080

    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000

    # Specify restart policy
    restart: unless-stopped

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
